### ISSUE TITLE
Support diskarray.take and diskarray.data

### ISSUE THREAD

**Issue by IdavalapatiRamanjaneyulu** [deep-compute/diskarray#11]
- diskarray.take:
If we want to take the data from diskarray then we need to specify diskarray[:].take. Instead of this it would be better to support take.

- The same with diskarray.data like if I want the data instead of specifying diskarray[:] support diskarray.data.

**Comment by jaswanth098** [comment]
haven't been working on this will come back to this later

**Comment by jaswanth098** [comment]
Not working on this actuvely

**Comment by sundarrajan78** [comment]
Assigning to @jaswanth098 and snoozing it for month

**Comment by sundarrajan78** [comment]
Low Priority

**Comment by sundarrajan78** [comment]
Low priority

**Comment by sundarrajan78** [comment]
Low priority

**Comment by sundarrajan78** [comment]
Not a priority
