### ISSUE TITLE
Support close method to close the file

### ISSUE THREAD

**Issue by IdavalapatiRamanjaneyulu** [deep-compute/diskarray#7]
```python
def close(self):
    del self.data
    self.data = None
```

**Comment by IdavalapatiRamanjaneyulu** [comment]
Even closing the file in DiskArray, mmap is not closing the file.

**Comment by prashanthellina** [comment]
@RamanjaneyuluIdavalapati Is this still a valid issue?

**Comment by IdavalapatiRamanjaneyulu** [comment]
@prashanthellina No. We have supported this here https://github.com/deep-compute/diskarray/commit/d1822fbd928f60d7358a5868630f702c478a6218 and forgot to close this issue.

We can close now.
