### ISSUE TITLE
If shape is not given then it would be better to assume the previous shape.

### ISSUE THREAD

**Issue by IdavalapatiRamanjaneyulu** [deep-compute/diskarray#9]
- Let us assume we gave shape as (4, 3) and append some arrays to diskarray and close it.
- When I open the diskarray second time and if I don't give the shape then it is giving 1D array.
- It would be better if I don't give the shape then assume the shape is (4, 3) and give the actual array.

**Comment by prashanthellina** [comment]
Perhaps we should store a manifest file alongside the actual data file.

**Comment by jaswanth098** [comment]
not working on this moving this to ready

**Comment by jaswanth098** [comment]
Not actively working on it

**Comment by sundarrajan78** [comment]
@jaswanth098 I am assigning to you and snoozing this for a month.
